version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      # - POSTGRES_DB=test
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 80:8000
    depends_on:
      - db
    # env_file:
    #   - ./.env.dev
    #   - ./.env.secrets
    volumes:
      - ./app/:/usr/src/app/

volumes:
  postgres_data:
