# Generated by Django 4.0.2 on 2022-02-22 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('code', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
                ('priority', models.BooleanField(default=False)),
                ('schedule', models.DateTimeField(null=True)),
                ('redirect_link', models.URLField(null=True)),
                ('lock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='link.linklock')),
            ],
        ),
    ]
