# Generated by Django 4.0.2 on 2022-02-22 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='lock',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='link.linklock'),
        ),
    ]
