# Generated by Django 4.0.2 on 2022-02-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_alter_link_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
