# Generated by Django 4.0.2 on 2022-02-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_link_is_live_link_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='lock',
        ),
        migrations.AddField(
            model_name='link',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='lock_type',
            field=models.CharField(blank=True, choices=[('date_of_birth', 'date_of_birth'), ('sensitive_content', 'sensitive_content'), ('code', 'code')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='LinkLock',
        ),
    ]
