# Generated by Django 4.0.2 on 2022-02-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_remove_link_lock_link_code_link_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='redirect_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
