# Generated by Django 4.0.2 on 2022-05-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0007_themes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Themes',
            new_name='Theme',
        ),
    ]
