# Generated by Django 4.0.2 on 2022-05-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0008_rename_themes_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.FileField(upload_to='themes'),
        ),
    ]
