# Generated by Django 4.0.2 on 2022-05-05 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('link', '0010_userlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='userauth.userprofile'),
        ),
    ]
