# Generated by Django 4.0.2 on 2022-05-07 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0011_alter_userlink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(null=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
