# Generated by Django 4.0.2 on 2022-05-07 14:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('link', '0012_alter_link_title_alter_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlink',
            name='links',
        ),
        migrations.RemoveField(
            model_name='userlink',
            name='theme',
        ),
        migrations.AddField(
            model_name='userlink',
            name='link',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='link.link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='userlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userauth.userprofile'),
        ),
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='link.theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='userauth.userprofile')),
            ],
        ),
    ]
