# Generated by Django 4.0.2 on 2022-05-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0013_remove_userlink_links_remove_userlink_theme_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLink',
        ),
    ]
