# Generated by Django 4.0.2 on 2022-05-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0014_delete_userlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
    ]
