# Generated by Django 4.0.2 on 2022-05-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('link', '0015_remove_link_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='link.link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userauth.userprofile')),
            ],
        ),
    ]
