# Generated by Django 4.0.2 on 2022-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0016_userlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
