# Generated by Django 4.1.2 on 2022-10-31 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
        ("link", "0018_alter_link_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="userauth.userprofile",
            ),
            preserve_default=False,
        ),
    ]
