# Generated by Django 4.1.2 on 2022-10-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("link", "0019_link_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserLink",
        ),
    ]
