# Generated by Django 4.1.2 on 2022-10-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("link", "0020_delete_userlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="position",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
