name: Linkhanger CI/CD workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  SECRET_KEY={{secrets.SECRET_KEY}}
  ALLOWED_HOSTS= 127.0.0.1 localhost
  CORS_ALLOWED_ORIGINS=localhost
  DB_NAME=postgres
  DB_USER=testuser
  DB_PASSWORD=testpassword
  DB_HOST=db
  DB_PORT=5432
  DJANGO_SETTINGS_MODULE=linkhanger.settings.production

jobs:
  build:
    name: Build Docker image and push to repos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v3
      - name: Login in to hub
        uses: docker/login-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: sreehariskumar/flaskapp:latest
      - name: deploying
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker image pull sreehariskumar/flaskapp:latest
            docker container stop flask
            docker container rm flask
            docker container run -d --name flask -p 80:5000 sreehariskumar/flaskapp