name: Linkhanger CI/CD workflow

on:
  push:
    branches: [main,'ci-correction']
  pull_request:
    branches: [main,'ci-correction']
env:
  SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
  ALLOWED_HOSTS: "127.0.0.1"
  CORS_ALLOWED_ORIGINS: "localhost"
  DB_NAME: postgres
  DB_USER: testuser
  DB_PASSWORD: testpassword
  DB_HOST: db
  DB_PORT: 5432
  DJANGO_SETTINGS_MODULE: linkhanger.settings.production

jobs:
  build:
    name: Build Docker image and push to repos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: deploying
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY}}
          port: 22
          script: |
            echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            sudo yum update -y
            sudo yum install git -y
            rm -rf linkhub
            cd ~/linkhanger
            git clone https://github.com/adityabohra007/linkhub
            echo "Pulling latest code..."
            git pull origin main
            docker-compose pull
            docker-compose down
            docker-compose up -d --build
            echo "Deployment complete ✅"
